[Variables]

Language=English
Location=SPXX0050
Unit=m
Format=H
Hidden=0
Hidden2=1
Player=KgMusic
PlayerPath=C:\Program Files (x86)\KuGou\KGMusic\KuGou.exe     

;This below is the settings for Folders

FolderName1=My Computer
FolderPath1=Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}

FolderName2=My Documents
FolderPath2=Shell:::{A8CDFF1C-4878-43be-B5FD-F8091C1C60D0}

FolderName3=Videos
FolderPath3=Shell:::{A0953C92-50DC-43bf-BE83-3742FED03C9C}

FolderName4=Pictures
FolderPath4=Shell:::{3ADD1653-EB32-4cb0-BBD7-DFA0ABB5ACCA}

FolderName5=Music
FolderPath5=Shell:::{1CF1260C-4DD0-4ebb-811F-33C572699FDE}

FolderName6=Downloads
FolderPath6=Shell:::{374DE290-123F-4565-9164-39C4925E467B}
