[Variables]

Language=English
Location=SPXX0050
Unit=f

FontColor=255,255,255
FontFace=Futura Lt

Player=KgMusic
PlayerPath=C:\Program Files (x86)\KuGou\KGMusic\KuGou.exe              

;-------------------------------------------------------------
;-------------------------------------------------------------

;Meny panel settings
;Enter your settings here:

Text1=- BaiDu
Text2=ZhuTiX
Text3=GuanChaZhe
Text4=ZhiHu
Text5=Bilibili
Text6=JingDong -

Path1=https://www.baidu.com/
Path2=https://zhutix.com/
Path3=http://www.guancha.cn/
Path4=https://www.zhihu.com/
Path5=https://space.bilibili.com/1580138
Path6=https://www.jd.com/

;-------------------------------------------------------------
;-------------------------------------------------------------

;Visualiser settings
;Please dont eddit these settings if you don't know what you doing

FFTSize=2048
FFTOverlap=1024
FFTAttack=650
FFTDecay=250
FreqMin=100
FreqMax=16000
Sensitivity=35
PlayerSwitch=0
